
# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Cultivate Cafe
email : cultivate.a.co.op.cafe@gmail.com
description: Fresh Healthy Local Delicious
BASE_PATH : https://jknowles.github.io/cultivate-cafe/
production_url : https://jknowles.github.io/cultivate-cafe/

facebook_username: cultivatecoopcafe
instagram_username: cultivate.a.co.op.cafe

# Build settings
collections:
  subpages:
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
